In [2]:
# importing required libraries

import pandas as pd
import matplotlib.pyplot as plt

In [17]:
# Importing csv data

savings_df = pd.read_csv('savings_data.csv')
savings_df.head(10)

     Month       Category     Type   Amount                    Notes
0  2024-01         Salary   Income  45000.0           Monthly salary
1  2024-01      Freelance   Income   8000.0          Tutoring income
2  2024-01           Rent  Expense  12000.0               House rent
3  2024-01           Food  Expense   6500.0      Groceries and meals
4  2024-01      Transport  Expense   2200.0             Bus and fuel
5  2024-01      Utilities  Expense   1800.0    Electricity and water
6  2024-01         Health  Expense   1500.0           Gym membership
7  2024-01  Entertainment  Expense   1200.0   Eating out and leisure
8  2024-01        Savings  Savings  27800.0  Monthly savings deposit
9  2024-02         Salary   Income  45000.0           Monthly salary

In [15]:
# Checking the data
savings_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Month     109 non-null    str
 1   Category  109 non-null    str
 2   Type      109 non-null    str
 3   Amount    107 non-null    float64
 4   Notes     109 non-null    str
dtypes: float64(1), str(4)
memory usage: 4.4 KB

In [11]:
# checking summary statistics
savings_df.describe()

             Amount
count    107.000000
mean   12893.457944
std    15301.234819
min      700.000000
25%     2050.000000
50%     6600.000000
75%    12000.000000
max    48000.000000